### ISSUE TITLE
Getting device name from Json filename is parsing incorrectly

### ISSUE THREAD

**Issue by knowroozi** [damianszczepanik/cucumber-reporting#176]
in Features.java

    public String getDeviceName() {
        String name = "";
        String[] splitedJsonFile = jsonFile.split("_");
        if (splitedJsonFile.length > 1)
            name = splitedJsonFile[0].substring(0, splitedJsonFile[0].length() - 1);
        return name;
    }

the endIndex of the substring method to parse the name of the device should not have the -1 because endIndex in String.substring() is exclusive, so its dropping the last character in this case

ex: I have a file named Nexus5.json being parsed and the device name that is coming through from this method is "Nexus" instead of Nexus5

**Comment by damianszczepanik** [comment]
As far as I remember there is no test for device name so it might work incorrectly.

Can you share some JSON example so this issue can be verified when patch is ready?

**Comment by knowroozi** [comment]
https://gist.github.com/knowroozi/d769e77a865bb385effc#file-nexus5-json

**Comment by knowroozi** [comment]
Sorry.  Rename to Nexus5_report.json

**Comment by damianszczepanik** [comment]
OK, I haven't launched cucumber-jwm with parallel mode so I need to get some information
1. What is device name and how it is passed from json file ( I can't see such information in your attachment)
2. Can you run parallel and having only one json file as the result?

**Comment by knowroozi** [comment]
I'm using the following tool to run tests in parallel using calabash -> https://github.com/rajdeepv/parallel_calabash 
This tool gets all the connected devices and runs the cucumber tests on them. 
It is possible for this to only be one device. 
It also writes the device model name to an environment variable which i am using to create the json file names for each test run.

    parallel_calabash -a my_app.apk ./features -o '--format json --out $DEVICE_INFO_report.json' --concurrent

the -o option represents the parameters passed to cucumber.

This generates the file in the gist posted above with the filename being <device_model_name>_report.json

**Comment by damianszczepanik** [comment]
@knowroozi 
So the device name is used in file name. Is that correct? If so how can you determine which part of the file is device name which is the rest?

**Comment by knowroozi** [comment]
That is correct.  I know the position of the device name in the string
because I am setting it in the command line arguments.  In this case it is
the first part of the string

**Comment by damianszczepanik** [comment]
Well, If I'm right - correct me if I'm wrong - that is the first part in your case because this is how you defined variable. However there is no problem to make it as postfix or even the whole name.

In that case there is no simple rule to decode this information in cucumber-plugin

**Comment by knowroozi** [comment]
That is correct.  I guess you would have to define it's usage how you would
expect it to be

**Comment by damianszczepanik** [comment]
With above patch the device would be taken from feature file name. This should be fix the problem permanently.

**Comment by brianeray** [comment]
I have a somewhat lengthy question about one of the commits associated with this issue. Some background: During a recent maintenance window I upgraded our Jenkins to the latest LTS core and, among other things, this plugin from 0.1.0 to 0.4.0. Subsequently, our publish steps started failing with this stack trace embedded in an error page:

```
java.io.FileNotFoundException: C:\Jenkins\jobs\UI_Automation_Dev\builds\674\cucumber-html-reports\features\mycompanysapp\part_of_the_app.feature.html (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.(FileOutputStream.java:213)
        at java.io.FileOutputStream.(FileOutputStream.java:162)
        at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:63)
        at net.masterthought.cucumber.generators.FeatureReportPage.generatePage(FeatureReportPage.java:32)
        at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:225)
        at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:140)...
```

Our Jenkins and Cucumber farm is primarily Windows-based, so the uri's within the cucumber.json report have double-backslashed path separators like this:

    "uri": "features\\mycompanysapp\\part_of_the_app.feature",

My suspicion fell on the new regex committed in SHA: d69b860b3f87715f2bac049172a868429bb84ebb to Feature.getFilename(), which does not seem to be greedy enough to conver the double backslashes to hyphens, at least in my testing via the Groovy shell. If so, downstream I think the FileOutputStream constructor chokes as above due to an illegal Windows filename.

**Finally the question**: Is the change to that regex committed in SHA: a4026e90f99d15b6167becc2c0f960c70ebd0b8f intended to correct this? It seems like it would correct this, as in my Groovy shell the new regex converts all the backslashes to hyphens.

**Comment by damianszczepanik** [comment]
Yes, the idea was to replace all characters that may not be valid (no matter on which OS you are running tests or report) so this should fix your problem

**Comment by brianeray** [comment]
Got it. Thank you.
