### ISSUE TITLE
Is it possible to have the report divided by folders? 

### ISSUE THREAD

**Issue by MadalinaSamoila** [damianszczepanik/cucumber-reporting#335]
Hi,

Is it possible to divide the report into sections by the folder name in which the json reports were found? To be more specific, we are running tests on multiple devices at the same time and dividing the reports into folders with the device name (such as Nexus 5, iPhone 6 etc.). It would be useful to have the end report show them explicitly, like:

**Nexus 5**
Test1
Test2
Test3

**iPhone 6**
Test1
Test2
Test3

I've been looking through the project and can't find anything that does this. Would it be possible to look into this, please?

Thank you!
Madalina

**Comment by tommywo** [comment]
@MadalinaSamoila try using setting 'parallelTesting' flag to true. Device name is taken from json filename.

**Comment by MadalinaSamoila** [comment]
So should I change the names of my json reports to include the device name?

**Comment by MadalinaSamoila** [comment]
So I got this working with device names and parallel running, however as the test suite might grow to hundreds of tests executed on tens of devices, one could be in for a lot of scrolling. Would it be possible to have an overview per device (test passed/failed/skipped), which can be expandable into the full list?

**Comment by damianszczepanik** [comment]
I don't practice parallel running execution thus I don't have plan to develop this feature. You can do this by pushing PR

**Comment by Seploid** [comment]
Hi @MadalinaSamoila ! 
We use the similar decision for our project - we execute our tests on different localizations in  parallel instead of devices as it need for you. 

After executing tests we have a few different folders with json-file and generated reports based on them. Then we merge these json-files in one and generate common report based on merged json-file and add references to subreports.

How it looks...
**Structure of target folder:**
![target_structure](https://cloud.githubusercontent.com/assets/14804782/13311491/5f69ac06-dba8-11e5-96d0-e7afa4face13.png)

**Common report with references on sub reports by localization:**
![cuc_rep](https://cloud.githubusercontent.com/assets/14804782/13311453/1eed2c20-dba8-11e5-88ba-a3e7d19c652d.png)

**Subreport**
![cuc_subrep](https://cloud.githubusercontent.com/assets/14804782/13311508/75265c56-dba8-11e5-9e75-5cedc135b746.png)

**Comment by Seploid** [comment]
@damianszczepanik , we will be glad to see this feature in your report-builder. I think, it is really needed

**Comment by damianszczepanik** [comment]
Sounds good but I don't have plan for supporting this in near future. You are more than welcome to prepare PR for this!

**Comment by damianszczepanik** [comment]
I recommend to use tags, folders won't be supported
