### ISSUE TITLE
Configuration to mark scenarios failed if hooks fail

### ISSUE THREAD

**Issue by midopa** [damianszczepanik/cucumber-reporting#497]
Hooks usually have code to setup or cleanup test data/environment. By having them marked as failures, they're easy to search/spot in the test report. But I understand not all users would like this. So it seems a configuration flag would be helpful.

**Comment by damianszczepanik** [comment]
@midopa @npgarcia @stevejensen22

What is your expectation when having following cases:
* @Before -> Undefined
* @Before -> Passed

or
* @Before -> Passed
* @After -> Failed

**Comment by stevejensen22** [comment]
I'm having a hard time following what you're asking. But I will try to set my expectation that should be applicable to all cases:

If at any time during the execution of the scenario, the `@Before, Background steps, Scenario steps, or @After` **fails**, the entire scenario should be marked as **FAILED**.

If your `@Before` and `@After` aren't directly relevant to the scenario, then you should implement Exception catching so they log the failure rather than fail the test (from a JUnit/TestNG perspective).

**Comment by damianszczepanik** [comment]
If and when the scenario can be marked as undefined/pending or any other status different than passed or failed?

**Comment by stevejensen22** [comment]
I would say the same rule applies? Just replace `FAILED` with `PENDING` or `UNDEFINED`.

**Comment by damianszczepanik** [comment]
So then read my question again and what about when tee statuses are different for steps and hooks?

**Comment by stevejensen22** [comment]
I have never encountered a scenario where the `@Before` fails and the `Scenario` passes. However, I have encountered where the `Scenario` passes and the `@After` fails, in which case, I added exception handling to simply log the error message rather than fail the test.  Failed cleanup, etc shouldn't cause the JUnit test to fail.

When have you seen a `@Before` fail and still have the `Scenario` actually run and `PASS`? I've only seen that the steps are all `Skipped`.

**Comment by npgarcia** [comment]
I agree with @stevejensen22 , the status of a scenario can't be passed if one of the steps in the `@Before` or `@After` or `Scenario` are `Failing`, `Skipped` or `Undefined`. 

If we only have two columns for the scenarios (Passed or Failed), then if any of the steps are not passing, then the scenario is failing. By consequence the feature as well.

**Comment by damianszczepanik** [comment]
This becomes more clear and reasonable to me. I also consider this configuration: https://raw.githubusercontent.com/jenkinsci/cucumber-reports-plugin/master/.README/advanced_options.png

Looks like after this change checkbox about pending/undefined/missing statuses are useless ?

What are your expectations about them?

**Comment by npgarcia** [comment]
So checkbox is to mark build as failed. The original request from https://github.com/jenkinsci/cucumber-reports-plugin/issues/65 was to count the scenario as failed in the first two columns of the report.

In this case, what is the difference between the build and the column passed in the report?

**Comment by damianszczepanik** [comment]
Checkbox lets you to define the build status (on Jenkins) so depends of the feature result you can fail whole build. Columns are only for presentation.

**Comment by damianszczepanik** [comment]
So I came up with some idea how to make the plugin powerful about configuring result. Take a look at attached proposal how you can decide when the report is failed and what should be done when it happens.

And the question is about hooks, again. There are three options when and how the hooks should be counter here:

- Add extra options for the hook but this makes the configuration quite complex because it can be after, before and each can have probably many statuses.
- not passing hooks changes the scenario to failure so if you want to count this you should update attached configuration according to scenarios
- other? then some helper should explain how and why hooks are counted differently what could be confusing for developers.

I'm waiting for your comments

![result](https://cloud.githubusercontent.com/assets/9612911/17834096/19e4f35a-6732-11e6-865d-a0ab8ed511c2.png)

**Comment by npgarcia** [comment]
Definitely having many options to configure a report makes the plug in powerful. And it makes is complex, as you mention. I personally prefer simplicity over complexity. Just a configuration to decide to mark my scenario fail if the hook failed, and if that means that the build failed.

Giving numbers to measure if the build is healthy or will make it complicated to keep updating it if you keep growing your tests overtime. But it might really be helpful if you are not adding new scenarios to your test suite.

**Comment by damianszczepanik** [comment]
Right so I finally propose to have numbers limitation without percentage. My motivation was to
- add some tolerance for tests that sometimes fail wg integration testa
- be able to not fail whole report only because some tests don't pass if they need to be updated or refactored or removed.

And as I said it better to have such option and don't use it than must use it but don't have possibility.

This should be treated like back door but I user should use it carefully.

**Comment by damianszczepanik** [comment]
Main problem of this issue has been solved however I believe you can also make it work by making pending/undefined/skipped steps failed. Then if the hook is not passed then scenario also will be failed
