### ISSUE TITLE
Feature (details) page is wrong for consolidated reports

### ISSUE THREAD

**Issue by christianbalzer** [damianszczepanik/cucumber-reporting#67]
I have the following feature file

```
@all
Feature: Search
As a user
I want to find stuff
So that I can use it

  @a
  Scenario: tag a
    Given tag "a"

  @b
  Scenario: tag b
    Given tag "b"

  @c
  Scenario: tag c
    Given tag "c"
```

and I run cucumber tests on Jenkins three times with `mvn test` and the following properties:
```
cucumber.options=src/test/resources/features --tags @a --format pretty:STDOUT --format html:target/cucumber-a --format json:target/cucumber-a.json
```
The tag and the file name for the json file are adjusted for each run.

The features overview table looks like this, which is OKish (though I wouldn't have minded consolidation into one row here):
![features-overview](https://cloud.githubusercontent.com/assets/2813098/3428723/f7288ada-0044-11e4-8899-46200dc9ca39.PNG)

However, every single link points to the same page, which only shows the last test run:
![feature-details](https://cloud.githubusercontent.com/assets/2813098/3428735/303c5dd8-0045-11e4-93b1-e5545a65288a.PNG)

The details for tags @a and @b are thus missing...

**Comment by patryk44** [comment]
I came across the same problem. Any update when this may be resolved?

**Comment by FaiMal** [comment]
Hi, I have the same issue. The report for the feature is not complete. Any solution for this?

**Comment by kingsleyh** [comment]
It requires a code change to fix. But I'm not sure when I could get to this - it's taken me almost a year to just do a release

**Comment by damianszczepanik** [comment]
I had the same problem in the past and I treated it as a bug but after a deep investigation I've changed my mind and I would call it a feature or software limitation.

If you have the same scenario name for more than one json file you will met above situation. Having the same scenario for a few json files means that:
- you are running the same feature from different contexts so results should be merged
- you are running two different feature (that have the same scenario name) and they should be treated as two different scenarios
- both above

Since it's hard to determine your intention it would be hard or impossible to catch all cases in report. We've decided to rename scenarios by putting context to the name and problem won't happen any more :-)
Additionally I've added test that verifies if feature files are unique (it names are the same mvn test fails). You can add the same for scenario outlines as well.

Based on above I would not change current implementation. We can add some log/debug but when report is generated by Jenkins such logs will be useless. If you have better idea let me know.

**Comment by joris77** [comment]
Hi,

I have the same problem. I run the same features with my selenium, spring integration and domain unit tests. Afterwards I want to see how my features are 'covered'. For this I would like the results of the scenarios be merged. For now I do not want to use tags I run the whole feature set for all types of tests.

@damianszczepanik why not add a flag to make your intentions clear merge = true/false

**Comment by damianszczepanik** [comment]
Are you running the same *.feature file for cucumber and unit? Or you have two *.feature file one for cucumber, another one for unit? Or I don't understand :)

**Comment by joris77** [comment]
The same feature file is used for a Selenium test and a domain unit test (both cucumber tests). In the Selenium test a happy flow scenario of the feature is tested. In the domain unit tests multiple corner cases of the feature are tested. 

I want to test features also with other tests than the end to end selenium test to keep the [test automation pyramid](http://martinfowler.com/bliki/TestPyramid.html) in shape.

After running both the tests I would like to see a merged (consolidated as christianbalzer calls it) result, so I can determine the 'feature coverage' (is that a valid term?). This way we can determine what must be tested manually or if extra automated tests have to be added.

You say you cannot determine my intention (consolidating/merging or not) and my suggestion is to add a flag to make my intention clear.

**Comment by damianszczepanik** [comment]
Sounds reasonable but I don't know if/when it would be possible. In the meantime you can manage this by keeping tests in different files and running tests by tag

**Comment by joris77** [comment]
I have some time to spare so I could help, but I think it is a rather big change. I had a quick look at the code and I think you need some kind of an intermediate model in java instead of the json model.

**Comment by damianszczepanik** [comment]
Based on my comments above that might be hard to handle: this is not technically impossible but adding one feature you will lost another.
