### ISSUE TITLE
OutOfMemory error with large JSON.

### ISSUE THREAD

**Issue by manuperera** [damianszczepanik/cucumber-reporting#682]
Hi,

I have a cucumber JSON file with 1034018 lines (37 MB). The plugin for Jenkins is producing a OutOfMemory error:

```
java.lang.OutOfMemoryError: Java heap space
```
![image](https://user-images.githubusercontent.com/28434493/32166954-b7e2b628-bd67-11e7-8ab6-63fa61af4c92.png)

I have configured Tomcat server where run Jenkins with 8GB of Heap. I don't understand because cucumber report plugin is using all the memory heap.

I appreciate any help you can give me.

Regards,

**Comment by damianszczepanik** [comment]
I see the parsing process has already be started and the failure was caused by velocity which tries to build the page. In that case what I can recommend is to increase Java memroy for Jenkins. 37MB is quite impressive report file

**Comment by manuperera** [comment]
Which is your recommendation aboout de size of memory. 10 GB??, 12 GB??. I would appreciate your opinion.

Regards,

**Comment by fmarmar** [comment]
Hi, I've been debugging this problem cause we are facing the same issue, and we couldn`t solve it increasing the memory.

The real problem is that we are creating and initializing one VelocityEngine instance for html we are going to create, keeping them in memory to later on writing the html to disk. I've been able to make a simply modification and keep the max heap size under 1.5GB.

Probably there is room for improvement, but it's a good improvement. If I get the time I will try to make a pull request. In the meantime, here is the modified file.

[ReportBuilder.zip](https://github.com/damianszczepanik/cucumber-reporting/files/1556675/ReportBuilder.zip)

**Comment by damianszczepanik** [comment]
Will be happy to accept this
