### ISSUE TITLE
Is it possible to use cucumber-reporting plugin through cucumber CLI Runner?

### ISSUE THREAD

**Issue by NameAlex** [damianszczepanik/cucumber-reporting#686]
I  would like to use cucumber-reporting through [cucumber CLI Runner ](https://cucumber.io/docs/reference/jvm#cli-runner). Now I use native cucumber plugin for html report generation, like passing arguments `--plugin html: /home/user/etc`. But it does not provide overlall statistic of executed test cases as it does "cucumber-reporting".

**Comment by damianszczepanik** [comment]
Well it does not and I don't have plan to support this unless someone (you?) send PR about it.

**Comment by monochromata** [comment]
I gave this a try at https://gitlab.com/monochromata-de/pretty-cucumber-reports-plugin . It works quite well up to this draft stage. But I did not figure out yet how to pass further information to the Cucumber formatter, like project name and the classifications. So this is not a complete solution yet.

I wonder whether https://github.com/damianszczepanik/maven-cucumber-reporting would be a better fit for @NameAlex's requirements, though. I found out about maven-cucumber-reporting after seeing the first report I generated myself. Maybe maven-cucumber-reporting could be linked prominently at https://github.com/damianszczepanik/cucumber-reporting ?

If https://gitlab.com/monochromata-de/pretty-cucumber-reports-plugin seems useful, I would also be happy to contribute it somewhere below https://github.com/damianszczepanik/ or as part of https://github.com/damianszczepanik/cucumber-reporting whatever @damianszczepanik thinks fits.

**Comment by damianszczepanik** [comment]
Contribution is more than welcome. I will be happy to accept PR

**Comment by monochromata** [comment]
I updated the cucumber reporter plugin in https://gitlab.com/monochromata-de/pretty-cucumber-reports-plugin with a mechanism to read project name, classifications etc. from a properties file.

I implemented it using cucumber-jvm 3.0.2. Because the cucumber formatter plugin has a direct dependency on cucumber that is not present in damianszczepanik/cucumber-reporting, I suggest you create a new repo damianszczepanik/cucumber-formatter-plugin . I would then adjust the package names to your namespace and send a pull request to that repo. You could then add your maven config to have the project built. What do you think?

**Comment by damianszczepanik** [comment]
Why do you want me to create repo which can be created by you? From my perspective it is more valuable as you are the main contributor (congrats!) and I don't have to maintain another project which I probably won't use

**Comment by monochromata** [comment]
Out of laziness - I'm most fine when I don't have to maintain things myself :-).

However, I now published https://gitlab.com/monochromata-de/cucumber-reporting-plugin . It's also available from the Central repository :-).
