### ISSUE TITLE
 How can I pass the jsonFiles parameter in the maven command

### ISSUE THREAD

**Issue by BLOPESLO** [damianszczepanik/cucumber-reporting#976]
Hi,
I need to execute comand maven mvn net.masterthought:maven-cucumber-reporting:5.3.0:generate to generate the report, but i getting the following error:
I suppose the 'jsonFiles' parameter is missing.

[ERROR] Failed to execute goal net.masterthought:maven-cucumber-reporting:5.3.0:generate (default-cli) on project template-web-CucumberSelenium: The parameters 'jsonFiles' for goal net.masterthought:maven-cucumber-reporting:5.3.0:generate are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

How can I pass the parameters in the maven command?
I tried it this way and didn't work.
I know that the parameters are in the following pom, but how can I pass them in the maven command?
https://github.com/damianszczepanik/maven-cucumber-reporting

mvn -DjsonFiles='/target/cucumber-reports/cucumber.json' net.masterthought:maven-cucumber-reporting:5.3.0:generate

Any idea?

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/maven-cucumber-reporting

**Comment by bbv888** [comment]
Long story short, as of version 5.5.0 you cannot set jsonFiles via the command line, only via the pom.
This is because within the plugin's code, the jsonFiles String Array is a Mojo parameter does not have an associated property attribute.

As a workaround, you can run "mvn verify -Dmaven.test.skip=true" after your Cucumber suite completes execution and your cucumber.json is created.
